### ISSUE TITLE
OptimisticLockのCheckVersion関数の修正

### ISSUE THREAD

**Issue by nrkt** [dbgroup-nagoya-u/cpp-utility#12]
OptimisticLockの`CheckVersion`関数について
現状は`kAllBitsMask`を使用してバージョンの一致を判定しているが，これだと他スレッドによって排他ロックを取得されている場合の判定ができないため，修正が必要そう．

以下の2つの方法が考えられる．
1. `CheckVersion`内で排他ロックが0になるまでスピンロックする
2. 排他ロックのbitまでを判定の対象とする

@baycedar 
修正の必要性と解決方法について何かあればお願いします！
(個人的には2つ目の方法が良さそう)

**Comment by baycedar** [comment]
忘れてました．たしかに排他ロックのビットも確認対象にしないとだめですね．確認時にスピンロックするのは無駄が多いので，後者の方法でお願いします．

**Comment by nrkt** [comment]
この関数修正したのですが，OMLの実装にあたって必要だったのではと思ったので再オープンしました．

OMLではSMOを判定する部分はロック無しで読んで，必要であればXLockを取ってSMOを実行するという過程になるので，判定する部分のバージョンとXLockを取った後のバージョンが一致しているかどうかを確認したいという気持ちになります．

@baycedar 
なので元々の関数も再び追加しようと考えていますが，どうでしょうか？
(関数名がちょっと難しい気がしています)

**Comment by baycedar** [comment]
そういう要求であれば，引数として`const size_t version`を受け取る`LockX`および`LockSIX`を用意して，バージョンが一致しているときのみ排他ないし排他意図共有ロックが取得できるという挙動にするといい感じな気がします．

**Comment by baycedar** [comment]
あと，このロック取得は失敗する可能性があるので，関数の名前も`TryLockX`と`TryLockSIX`にしておくといいかもですね．
